<<<<<<< HEAD
# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - "Write a tweet about {{topic}}"
  - "Write a concise, funny tweet about {{topic}}"
  

providers:
  - "openai:gpt-5-mini"
  - "openai:gpt-5"
  

tests:
  - vars:
      topic: bananas

  - vars:
      topic: avocado toast
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: avocado

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  - vars:
      topic: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: ensure that the output is funny

=======
description: "Automatización de Pruebas para un Moderador de Comentarios Tech"

prompts:
  - |
    Eres un moderador de comentarios de una plataforma educativa.
    Analiza cada comentario y responde únicamente con un JSON válido.
    El JSON debe tener estas claves:
    - "categoria": {"pregunta", "felicitación", "inapropiado"}
    - "accion": {"publicar", "bloquear"}
    - "es_respetuoso": {true, false}

    consulta: {{comentario}}

providers:
  - "google:gemini-3-flash-preview" # Modelo de IA que que utiliza

tests:
  # Caso 1: Duda técnica
  - vars:
      comentario: "Profesor, ¿Qué significa un array en JavaScript?" 
    assert:
      - type: is-json 
      - type: contains # Contenedor de: Categoria
        value: "pregunta"
      - type: icontains # Contenedor de: es_respetuoso
        value: "true"

  # Caso 2: Comentario ofensivo
  - vars:
      comentario: "El profesor no sabe nada de lo que dice" 
    assert:
      - type: is-json 
      - type: contains # Contenedor de: Categoria
        value: "inapropiado"
      - type: icontains # Contenedor de: es_respetuoso
        value: "false"  

  # Caso 3: Mensaje de Agradecimiento
  - vars:
      comentario: "Gracias al profesor Juan he aprendido programación" 
    assert:
      - type: is-json 
      - type: contains # Contenedor de: Categoria
        value: "felicitación"
      - type: icontains # Contenedor de: es_respetuoso
        value: "true"
>>>>>>> develop
